// Checks the Firestore rules for project requests against the emulator.
import {initializeApp} from "firebase/app";
import {getAuth,connectAuthEmulator,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut} from "firebase/auth";
import {getFirestore,connectFirestoreEmulator,doc,setDoc,getDoc,getDocs,collection,addDoc,updateDoc,deleteDoc,query,where} from "firebase/firestore";
const P="demo-tracker";
const mk=n=>{const a=initializeApp({projectId:P,apiKey:"demo"},n);const au=getAuth(a);connectAuthEmulator(au,"http://127.0.0.1:9099",{disableWarnings:true});const db=getFirestore(a);connectFirestoreEmulator(db,"127.0.0.1",8080);return{au,db}};
async function user(n,email){const c=mk(n);await createUserWithEmailAndPassword(c.au,email,"secret123");
  const r=await (await fetch(`http://127.0.0.1:9099/emulator/v1/projects/${P}/oobCodes`)).json();
  if(!r.oobCodes.find(x=>x.email===email)){await fetch(`http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:sendOobCode?key=demo`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestType:"VERIFY_EMAIL",idToken:await c.au.currentUser.getIdToken()})})}
  const codes=(await (await fetch(`http://127.0.0.1:9099/emulator/v1/projects/${P}/oobCodes`)).json()).oobCodes.filter(x=>x.email===email);await fetch(codes.pop().oobLink);
  await c.au.currentUser.reload();await c.au.currentUser.getIdToken(true);return c}
const ok=async(label,p,expect=true)=>{try{await p;console.log(expect?"PASS":"FAIL",label,"(allowed)")}catch(e){console.log(expect?"FAIL":"PASS",label,"(denied)",expect?e.code:"")}};
const owner=await user("o","clint@example.com");
const jim=await user("j","jim@example.com");
await setDoc(doc(owner.db,"access/jim@example.com"),{name:"Jim"});
await setDoc(doc(owner.db,"projects/p1"),{name:"Roof"});
const anon=mk("anon");
const good={name:"Amy",email:"amy@example.com",title:"Fix sink",description:"Drips",type:"maintenance",priority:"Normal",status:"new",at:new Date().toISOString(),via:"web"};
await ok("anonymous sends a request",addDoc(collection(anon.db,"requests"),good));
await ok("anonymous request with extra field",addDoc(collection(anon.db,"requests"),{...good,admin:true}),false);
await ok("anonymous request marked accepted",addDoc(collection(anon.db,"requests"),{...good,status:"accepted"}),false);
await ok("anonymous request missing title",addDoc(collection(anon.db,"requests"),{...good,title:""}),false);
await ok("anonymous request with huge details",addDoc(collection(anon.db,"requests"),{...good,description:"x".repeat(5000)}),false);
await ok("anonymous request pretending to be a user",addDoc(collection(anon.db,"requests"),{...good,by:"someone"}),false);
await ok("anonymous reads requests",getDocs(collection(anon.db,"requests")),false);
await ok("anonymous reads projects",getDocs(collection(anon.db,"projects")),false);
const r=await addDoc(collection(anon.db,"requests"),good);
await ok("anonymous edits a request",updateDoc(doc(anon.db,"requests/"+r.id),{status:"accepted"}),false);
await ok("signed-in follower sends a request as themselves",addDoc(collection(jim.db,"requests"),{...good,via:"app",by:jim.au.currentUser.uid}));
await ok("follower reads requests",getDocs(collection(jim.db,"requests")),false);
await ok("follower reads one request",getDoc(doc(jim.db,"requests/"+r.id)),false);
await ok("follower still reads projects",getDocs(collection(jim.db,"projects")));
await ok("follower still reads project updates",getDocs(collection(jim.db,"projects/p1/updates")));
await ok("follower edits a request",updateDoc(doc(jim.db,"requests/"+r.id),{status:"declined"}),false);
await ok("owner reads requests",getDocs(collection(owner.db,"requests")));
await ok("owner accepts a request",updateDoc(doc(owner.db,"requests/"+r.id),{status:"accepted",projectId:"p1"}));
await ok("owner adds a request with any fields",addDoc(collection(owner.db,"requests"),{...good,note:"phoned in"}));
await ok("owner deletes a request",deleteDoc(doc(owner.db,"requests/"+r.id)));
const stranger=await user("s","stranger@example.com");
const kn=(c,e,extra={})=>setDoc(doc(c.db,"knock/"+e),{email:e,name:"Stranger",uid:c.au.currentUser.uid,at:new Date().toISOString(),...extra});
await ok("stranger leaves their name",kn(stranger,"stranger@example.com"));
await ok("stranger overwrites it",kn(stranger,"stranger@example.com"),false);
await ok("stranger knocks as someone else",kn(stranger,"boss@example.com"),false);
await ok("stranger adds extra fields",setDoc(doc(stranger.db,"knock/x@example.com"),{email:"stranger@example.com"}),false);
await ok("anonymous knocks",setDoc(doc(anon.db,"knock/a@example.com"),{email:"a@example.com",name:"",uid:"x",at:"now"}),false);
await ok("stranger reads knocks",getDocs(collection(stranger.db,"knock")),false);
await ok("follower reads knocks",getDocs(collection(jim.db,"knock")),false);
await ok("owner reads knocks",getDocs(collection(owner.db,"knock")));
await ok("owner ignores a knock",updateDoc(doc(owner.db,"knock/stranger@example.com"),{ignored:true}));
await ok("owner lets them in",setDoc(doc(owner.db,"access/stranger@example.com"),{name:"Stranger"}));
await ok("let-in person reads projects",getDocs(collection(stranger.db,"projects")));
await ok("owner clears the knock",deleteDoc(doc(owner.db,"knock/stranger@example.com")));
// notes: followers add them, only the owner approves, nobody else sees them until approved
const jid=jim.au.currentUser.uid,sid=stranger.au.currentUser.uid,note=(extra={})=>({projectId:"p1",text:"Gate is sticking",author:jid,at:new Date().toISOString(),status:"pending",...extra});
const n1=await addDoc(collection(jim.db,"notes"),note());console.log("PASS follower adds a pending note");
await ok("follower adds an already-approved note",addDoc(collection(jim.db,"notes"),note({status:"approved"})),false);
await ok("follower adds a note as someone else",addDoc(collection(jim.db,"notes"),note({author:sid})),false);
await ok("follower adds a note with extra fields",addDoc(collection(jim.db,"notes"),note({decidedAt:"x"})),false);
await ok("anonymous adds a note",addDoc(collection(anon.db,"notes"),note()),false);
await ok("follower approves their own note",updateDoc(doc(jim.db,"notes/"+n1.id),{status:"approved"}),false);
await ok("follower reads their own notes",getDocs(query(collection(jim.db,"notes"),where("author","==",jid))));
await ok("follower reads approved notes",getDocs(query(collection(jim.db,"notes"),where("status","==","approved"))));
await ok("follower reads every note",getDocs(collection(jim.db,"notes")),false);
await ok("other follower reads the pending note",getDoc(doc(stranger.db,"notes/"+n1.id)),false);
await ok("owner reads every note",getDocs(collection(owner.db,"notes")));
await ok("owner approves the note",updateDoc(doc(owner.db,"notes/"+n1.id),{status:"approved",decidedAt:"now"}));
await ok("other follower reads it once approved",getDoc(doc(stranger.db,"notes/"+n1.id)));
await ok("owner adds a note directly",addDoc(collection(owner.db,"notes"),{projectId:"p1",text:"x",author:"o",at:"now",status:"approved"}));
process.exit(0);
